services:
  model:
    build: ./model
    ports:
      - "5000:5000"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MODEL_API_URL=http://model:5000
    depends_on:
      - model

networks:
  summarizer_network:
    driver: bridge